name: PHP CS Fixer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Require PHP CS Fixer
      run: composer global require friendsofphp/php-cs-fixer

    - name: Run php-cs-fixer
      run: php-cs-fixer fix --dry-run src/
