name: PHP Tests

on: [push]

jobs:
  coding-guidelines:
    name: Coding Guidelines

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run friendsofphp/php-cs-fixer
        run: php7.3 ./tools/php-cs-fixer fix --diff-format=udiff --dry-run --show-progress=dots --using-cache=no --verbose src/

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install ChromeDriver
      run: |
        sudo apt-get install chromium-chromedriver \
        && chromedriver --version

    - name: Install Symfony
      run: |
        wget https://get.symfony.com/cli/installer -O - | bash
        mv /home/runner/.symfony/bin/symfony /usr/local/bin/symfony
        symfony -v

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile

    - name: Build encore
      run: yarn dev

    - name: Prepare database
      run: |
        php bin/console --env=test doctrine:database:create -n
        php bin/console --env=test doctrine:schema:create -n
        php bin/console --env=test doctrine:fixtures:load -n

    - name: Start dev server
      run: symfony serve

    - name: Run test suite
      run: php bin/phpunit
